INSERT INTO ea_settings (name, value) VALUES
    ('google_analytics_code', ''),
    ('customer_notifications', '1'),
    ('date_format', 'DMY'),
    ('time_format', '24HR'),
    ('max_date', '30'),
    ('interval_time', '30'),
    ('reminder_days_out', '1,3'),
    ('theme_color', 'green'),
    ('week_starts_on', 'sunday'),
    ('show_free_price_currency', 'yes'),
    ('show_any_provider', 'yes');

INSERT INTO `ea_cellcarrier` (`id`, `cellco`, `cellurl`) VALUES
(1, 'Bell', '@txt.bell.ca'),  
(2, 'Bell Mobility', '@txt.bellmobility.ca'),  
(3, 'Koodo Mobile', '@msg.koodomobile.com'),  
(4, 'Fido (Microcell)', '@fido.ca'),  
(5, 'Manitoba Telecom Systems', '@text.mtsmobility.com'),  
(6, 'NBTel', '@wirefree.informe.ca'),  
(7, 'PageNet', '@pagegate.pagenet.ca'),  
(8, 'Rogers', '@pcs.rogers.com'),  
(9, 'Sasktel', '@sms.sasktel.com'),  
(10, 'Telus', '@msg.telus.com'),  
(11, 'Virgin Mobile', '@vmobile.ca'), 
(12, 'AT&T', '@mms.att.net'),
(13, 'T-Mobile', '@tmomail.net'),
(14, 'Verizon', '@vtext.com'),
(15, 'Sprint', '@messaging.sprintpcs.com'),
(16, 'Sprint PM', '@pm.sprint.com'),
(17, 'Virgin Mobile', '@vmobl.com'),
(18, 'Tracfone', '@mmst5.tracfone.com'),
(19, 'Metro PCS', '@mymetropcs.com'),
(20, 'Boost Mobile', '@myboostmobile.com'),
(21, 'Cricket', '@sms.mycricket.com'),
(22, 'Alltel', '@message.alltel.com'),
(23, 'Ptel', '@ptel.com'),
(24, 'Suncom', '@tms.suncom.com'),
(25, 'Qwest', '@qwestmp.com'),
(26, 'U.S. Cellular', '@email.uscc.net');