#!/bin/bash

echo "➜ Install Composer Dependencies"
composer install

echo "➜ Install NPM Dependencies"
npm install

echo "➜ Build Project Assets"
npx gulp build

echo "➜ Listen To Incoming Requests"
php-fpm
